// Hardcoded products
export const products = [
    {
        name: 'Brødkniv',
        price: 1000,
        currency: 'NOK',
        id: 1,
        url: '/sample.jpg',
    },
    {
        name: 'Bøtte',
        price: 2000,
        currency: 'NOK',
        url: '/sample.jpg',
        id: 2,
    },
    {
        name: 'Skje',
        price: 500,
        url: '/sample.jpg',
        currency: 'NOK',
        id: 3,
    },
    {
        name: 'Gaffel',
        price: 20,
        url: '/sample.jpg',
        id: 4,
        currency: 'NOK',
    },
    {
        name: 'Skap',
        price: 100,
        url: '/sample.jpg',
        id: 5,
        currency: 'NOK',
    },
    {
        name: 'Skap',
        price: 100,
        url: '/sample.jpg',
        id: 6,
        currency: 'NOK',
    },
    {
        name: 'Skap',
        price: 100,
        url: '/sample.jpg',
        id: 7,
        currency: 'NOK',
    },
    {
        name: 'Skap',
        price: 100,
        url: '/sample.jpg',
        id: 8,
        currency: 'NOK',
    },
    {
        name: 'Skap',
        price: 100,
        url: '/sample.jpg',
        id: 9,
        currency: 'NOK',
    },
    {
        name: 'Skap',
        price: 100,
        url: '/sample.jpg',
        id: 10,
        currency: 'NOK',
    },
    {
        name: 'Skap',
        price: 100,
        url: '/sample.jpg',
        id: 11,
        currency: 'NOK',
    },
    {
        name: 'Skap',
        price: 100,
        url: '/sample.jpg',
        id: 12,
        currency: 'NOK',
    },
    {
        name: 'Skap',
        price: 100,
        url: '/sample.jpg',
        id: 13,
        currency: 'NOK',
    },
    {
        name: 'Skap',
        price: 100,
        url: '/sample.jpg',
        id: 14,
        currency: 'NOK',
    },
    {
        name: 'Skap',
        price: 100,
        url: '/sample.jpg',
        id: 15,
        currency: 'NOK',
    },
    {
        name: 'Skap',
        price: 100,
        url: '/sample.jpg',
        id: 16,
        currency: 'NOK',
    },
];
